/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.delimare.pmb.gui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.delimare.pmb.connection.Koneksi;
import org.delimare.pmb.entity.CalonMahasiswa;
import org.delimare.pmb.entitymanager.PesertaManager;
import org.delimare.pmb.function.Alert;
import org.delimare.pmb.function.Logger;
import org.delimare.pmb.function.Utils;
import org.delimare.pmb.gui.dialog.DialogUbahStatusPendaftaran;
import org.delimare.pmb.gui.events.EventFormClosed;
import org.delimare.pmb.gui.tables.JTablePeserta;

/**
 *
 * @author smart user
 */
public class FormPeserta extends javax.swing.JFrame {

    private PesertaManager manager;
    private JTablePeserta sTable;

    private CalonMahasiswa calon;
    
    private Koneksi db;

    public FormPeserta() {
        initComponents();

        setLocationRelativeTo(null);
        
        db = new Koneksi();
        manager = new PesertaManager();
        sTable = new JTablePeserta();

        tablePeserta.setModel(sTable);

        loadData();
    }

    private void loadData() {
        try {
            sTable.setList(manager.getSemua(txtCari.getText()));
        } catch (Exception e) {
            Logger.error(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePeserta = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btnTambahPeserta = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnUbahStatus = new javax.swing.JButton();
        btnCetakReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablePeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePeserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesertaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePeserta);

        btn_simpan.setText("Keluar");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btnTambahPeserta.setText("Tambah Peserta");
        btnTambahPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPesertaActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnUbahStatus.setText("Ubah status");
        btnUbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahStatusActionPerformed(evt);
            }
        });

        btnCetakReport.setText("Cetak Report");
        btnCetakReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakReportActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Calon Mahasiswa");

        jLabel2.setText("Cari");

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariKeyTyped(evt);
            }
        });

        jButton1.setText("Cetak Jadwal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambahPeserta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 567, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUbahStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCetakReport))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btnUbah)
                    .addComponent(btnUbahStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapus)
                    .addComponent(btnTambahPeserta)
                    .addComponent(btnCetakReport)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPesertaActionPerformed
        FormTambahPeserta form = new FormTambahPeserta();
        Utils.openFrame(this, form, false);
        form.setFormClosedListener(new EventFormClosed() {
            @Override
            public void onClosed() {
                loadData();
            }
        });
    }//GEN-LAST:event_btnTambahPesertaActionPerformed

    private void btnUbahStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahStatusActionPerformed
        if (calon == null) {
            Alert.warning("Mohon pilih salah satu data untuk diubah");
            return;
        }
        
        DialogUbahStatusPendaftaran ubahStatus = new DialogUbahStatusPendaftaran(calon);
        ubahStatus.setOnFormClosed(new EventFormClosed() {
            @Override
            public void onClosed() {
                loadData();
            }
        });
        ubahStatus.setVisible(true);
    }//GEN-LAST:event_btnUbahStatusActionPerformed

    private void tablePesertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesertaMouseClicked
        int row = tablePeserta.rowAtPoint(evt.getPoint());

        int id = Integer.parseInt(tablePeserta.getValueAt(row, 0).toString());
        String nama = tablePeserta.getValueAt(row, 1).toString();
        String prodi = tablePeserta.getValueAt(row, 4).toString();
        String statusPendaftaran = tablePeserta.getValueAt(row, 5).toString();
        
        calon = new CalonMahasiswa();
        calon.setId(id);
        calon.setNamaLengkap(nama);
        calon.setProgramStudi(prodi);
        calon.setStatusPendaftaran(statusPendaftaran);
    }//GEN-LAST:event_tablePesertaMouseClicked

    private void btnCetakReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakReportActionPerformed
        try {
            String current = new File(".").getAbsolutePath();
            String path = current + "/src/org/delimare/pmb/gui/reports/CalonMahasiswaReport.jasper";
            JasperReport jr = (JasperReport) JRLoader.loadObject(new FileInputStream(new File(path)));
            JasperPrint jp = JasperFillManager.fillReport(jr, null, db.getConnection());
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            Logger.error(this, ex.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.error(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnCetakReportActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (calon == null) {
            Alert.warning("Mohon pilih salah satu data untuk diubah");
            return;
        }
        
        FormTambahPeserta form = new FormTambahPeserta(calon.getId());
        Utils.openFrame(this, form, false);
        form.setFormClosedListener(new EventFormClosed() {
            @Override
            public void onClosed() {
                loadData();
            }
        });
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyTyped
        
    }//GEN-LAST:event_txtCariKeyTyped

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        loadData();
    }//GEN-LAST:event_txtCariKeyReleased

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        Utils.openFrame(this, new FormUtama(), true);
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String current = new File(".").getAbsolutePath();
            String path = current + "/src/org/delimare/pmb/gui/reports/JadwalUjianReport.jasper";
            JasperReport jr = (JasperReport) JRLoader.loadObject(new FileInputStream(new File(path)));
            JasperPrint jp = JasperFillManager.fillReport(jr, null, db.getConnection());
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            Logger.error(this, ex.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.error(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if (calon == null) {
            Alert.warning("Mohon pilih salah satu data untuk dihapus");
            return;
        }
        
        int result = Alert.confirm("Yakin ingin menghapus data ini?");
        if (result == JOptionPane.YES_OPTION) {
            manager.delete(calon.getId());
            loadData();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeserta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPeserta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakReport;
    private javax.swing.JButton btnTambahPeserta;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbahStatus;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePeserta;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
